EcommerceApp.Web/Components/CategoriesMenuViewComponent.cs
using EcommerceApp.Application.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceApp.Web.Components
{
    public class CategoriesMenuViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;

        public CategoriesMenuViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var response = await _categoryService.GetAllCategoriesAsync();
            return View(response.Value);
        }
    }
}

EcommerceApp.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcommerceApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EcommerceApp.Web.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />

</head>
<body>

    <main class="dashboard">
        <div class="row h-100">
            <div class="col-2 col-md-2 bg-light sidebar">
                <div class="position-fixed pt-3 text-light ">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="/dashboard"><i class="fa-solid fa-gauge mx-2"></i> Dashboard</a>
                            <hr class="text-black m-0" />
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/category"><i class="fa-solid fa-list mx-2"></i> Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/product"><i class="fas fa-box mx-2"></i> Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fas fa-shopping-cart mx-2"></i> Orders</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="/Account/Logout"><i class="fas fa-sign-out-alt m-2"></i> Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col col-md">
                <div class="text-end my-2 p-2 bg-light">Hi Superadmin</div>
                <section>
                    @RenderBody()
                </section>
            </div>
        </div>
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/lib/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: '.tinymce-editor',
            license_key: 'gpl',
            toolbar: true, // Disable toolbar completely
            menubar: false, // Disable menubar
            branding: false, // Disable TinyMCE branding
            statusbar: false, // Disable status bar at the bottom
            height: 500,
            placeholder: 'Add content...',
            content_style: "body { font-family: 'Poppins', sans-serif; }",
            paste_preprocess: function (plugin, args) {
                // Remove href attributes and replace <a> with <p>
                args.content = args.content.replace(/<a[^>]*>(.*?)<\/a>/g, '$1');

                // Remove div tags and unwrap their contents
                args.content = args.content.replace(/<div[^>]*>/g, '')
                    .replace(/<\/div>/g, '');

                args.content = args.content.replace(/ class="[\w\s-]*"/g, '')
                    .replace(/ style="[^"]*"/g, '')
                    .replace(/ id="[\w-]*"/g, '')
                    .replace(/ data-selectable-paragraph="[^"]*"/g, '')
                    .replace(/ data-\w+="[^"]*"/g, '');
            }
        });
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        var successMessage = '@TempData["SuccessMessage"]';
        var infoMessage = '@TempData["InfoMessage"]';
        var errorMessage = '@TempData["ErrorMessage"]';
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EcommerceApp.Web/Views/Shared/_Footer.cshtml
<div class="footer bg-dark py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <h5>About Us</h5>
                <p class="about-text">
                    Welcome to eBazar, your one-stop destination for shopping smart and living better. Our dynamic eCommerce platform is designed to connect buyers with a wide range of high-quality products across multiple categories — from everyday essentials to exclusive finds.
                </p>
            </div>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-6">
                        <ul class="list-unstyled">
                            <li class="mb-2"><a href="#">About Us</a></li>
                            <li class="mb-2"><a href="#">Advertise</a></li>
                            <li class="mb-2"><a href="#">Careers</a></li>
                            <li class="mb-2"><a href="#">Subscribes</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="list-unstyled">
                            <li class="mb-2"><a href="#">Travel</a></li>
                            <li class="mb-2"><a href="#">Lifestyle</a></li>
                            <li class="mb-2"><a href="#">Sports</a></li>
                            <li class="mb-2"><a href="#">Nature</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <h5 class="text-light">Connect With Us</h5>
                <div class="social-icons">
                    <a href="#" class="mx-2" title="facebook"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="mx-2" title="twitter"><i class="fab fa-twitter"></i></a>
                    <a href="#" class="mx-2" title="instagram"><i class="fab fa-instagram"></i></a>
                    <a href="#" class="mx-2" title="mail"><i class="fas fa-envelope"></i></a>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-12 ">
                <p class="text-center">Copyright © 2025 All rights reserved | eBazzar</p>
            </div>
        </div>
    </div>
</div>

EcommerceApp.Web/Views/Shared/_Header.cshtml
<header class="sticky-top">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">eBazzar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                <ul class="navbar-nav d-flex">

                    @await Component.InvokeAsync("CategoriesMenu") 
                    <li class="nav-item mx-2">
                        <a asp-action="index" asp-controller="cart" class="nav-link text-dark"><i class="fa-solid fa-cart-shopping mx-2"></i></a>
                    </li>

                    

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item mx-4">
                            <div class="dropdown">
                                <button title="@User.Identity.Name" class="btn dropdown-toggle user-icon" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-solid fa-user"></i>
                                </button>

                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                                    <li><a class="dropdown-item py-2" asp-action="Profile" asp-controller="Account"><i class="fa-solid fa-user mx-2 fs-5"></i> Profile</a></li>
                                    <li><a class="dropdown-item py-2" asp-controller="Account" asp-action="Logout"> <i class="fa-solid fa-right-from-bracket mx-2 fs-5"></i> Sign out</a></li>
                                </ul>
                            </div>
                        </li>
                    }
                    else
                    {

                        <li class="nav-item mx-2">
                            <button type="button" class="btn btn-Secondary border rounded-pill" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                Get Started
                            </button>
                        </li>

                    }

                    <li class="nav-item mx-2">
                        <a href="#" class="nav-link text-dark"><i class="fa-solid fa-magnifying-glass"></i></a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header border-0">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body signin-modal">
                <div class="mb-4"><h3 class="text-center">Join eBazzar</h3></div>

                @{
                    var returnUrl = Context.Request.Path + Context.Request.QueryString;
                }

                <div id="loginSection">
                    @await Html.PartialAsync("_LoginPartial", new EcommerceApp.Application.DTOs.Auth.LoginDto() { ReturnUrl = returnUrl })
                </div>

                <div id="registerSection" style="display:none;">
                    @await Html.PartialAsync("_RegisterPartial", new EcommerceApp.Application.DTOs.Auth.RegisterDto())
                </div>

                <div class="my-3 text-center " id="createAccountLinkSection">
                    <p>No account? <a href="#" id="createAccountLink"><u>Create one</u></a></p>
                </div>

                <div class="text-center privacy-policy">
                    <p>Click “Sign in” to agree to eBazzar Terms of Service and acknowledge that eBazzar Privacy Policy applies to you.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

<script>
        $('#createAccountLink').on('click', function (e) {
        e.preventDefault();
        $('#loginSection').hide();
        $('#registerSection').show();
        $('#createAccountLinkSection').hide();
    });
</script>

EcommerceApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online Shopping Platform</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EcommerceApp.Web.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />

</head>
<body>
    @await Html.PartialAsync("_Header")
    <main role="main">
        @RenderBody()
    </main>

    @await Html.PartialAsync("_Footer")

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        var successMessage = '@TempData["SuccessMessage"]';
        var infoMessage = '@TempData["InfoMessage"]';
        var errorMessage = '@TempData["ErrorMessage"]';
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EcommerceApp.Web/Views/Shared/_RegisterPartial.cshtml
@model EcommerceApp.Application.DTOs.Auth.RegisterDto

<form asp-controller="Account" asp-action="Register" method="post" class="px-2" id="registerForm">

    <div class="mb-3">
        <div class="form-floating">
            <input asp-for="FullName" class="form-control" id="floatingFullName" placeholder="Full Name">
            <label asp-for="FullName"></label>
        </div>
        <span asp-validation-for="FullName" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <div class="form-floating">
            <input asp-for="Email" class="form-control" id="floatingEmail" placeholder="You@example.com">
            <label asp-for="Email"></label>
        </div>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <div class="form-floating position-relative">
            <input asp-for="Password" class="form-control pe-5" id="floatingPassword" placeholder="Password">
            <label asp-for="Password"></label>
            <i class="fa-solid fa-circle-info"
               data-bs-toggle="tooltip"
               data-bs-placement="right"
               title="Create a strong password: Use at least 8 characters, including upper/lowercase letters, digits, and symbols."
               style="cursor: pointer; position: absolute; right: 10px; top: 50%; transform: translateY(-50%);"></i>
        </div>
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <div class="form-floating">
            <input asp-for="ConfirmPassword" class="form-control" id="floatingConfirmPassword" placeholder="Confirm Password">
            <label asp-for="ConfirmPassword"></label>
        </div>
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
    </div>

    <div id="errorContainer1"></div>

    <div class="form-group text-center px-4">
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </div>
</form>

<div class="my-3 text-center">
    <p>Already Have account? <a href="#" id="loginLink">Login Now</a></p>
</div>

<script>
    $(document).ready(function () {
    $('#loginLink').on('click', function (e) {
        e.preventDefault();
        $('#loginSection').show();
        $('#registerSection').hide();
        $('#createAccountLinkSection').show();
    });

        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
        tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl);
        });

        $('#registerForm').submit(function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function (response) {
                    if (response.success) {
                        window.location.href = response.redirectUrl;
                    } else {
                        $('#errorContainer1').html('');
                        for (var error of response.errors) {
                            $('#errorContainer1').append('<div class="bg-danger text-light mb-2 py-2 text-center">' + error + '</div>');
                        }
                    }
                },
                error: function (xhr, status, error) {
                    $('#errorContainer1').html('<div class="text-danger">An unexpected error occurred. Please try again later.</div>');
                }
            });
        });
    });
</script>